1. M/L VS D/L

2. ANN, DNN, CNN, RNN -> LLM

3. Tensor : 현실 세계의 데이터를 딥러닝 모델이 인식할 수 있는 형태로 변환된 상태의 개채
- scalar
- vector
- matrix
- N-tensor

4. 인간의 뇌구조 > D/L 모델 확립

5. 시그모이드 함수 > 입력값 -> 가중치(w) + 편향(b) -> 출력층 : 0 ~ 1

6. 1차함수, 2차함수
- y = ax + b : a(기울기 = 가중치), b(절편 = 편향)
- y = ax^2

7. 미분
- 그래프 내 한 점에서의 기울기를 미분
- 실제값 = 예상값 (딥러닝 학습.예측)
- y = 5x + 1 => y' = 5
- y = 5x^2 + 1 => y' = 10x
- 상미분 : x (독립변수) 1개
- 편미분 : x (독립변수) 2개 이상
- y = 5a^2 + 2b + 1 => 변수 2개

8. 딥러닝의 예측값, 향상 시키기 위한 방법
- 가중치 (기울기) + 편향 (절편) => 실제값 & 예측(상)값
- 실제값 - 예측값 = 잔차 (residual)
- 비용함수 (cost function) : 잔차의 값을 최소화할 수 있도록 해주는 함수

9. 비용함수에서 사용가능한 기법
- MAE : 평균절대오차
- *MSE : 평균제곱근오차
- RMSE : 평균제곱근편차
- RMSLE : 평균제곱근대수오차

10. 최소제곱법
- 결국 잔차를 구하는 공식 => 2차 함수 => 독립변수 2개 (가중치, 편향)
- 기울기 계산 => 미분 => 편미분 계산
- 실제값 = 예측값 => 편미분 = 0
- 실제값과 가장 유사한 w, b

11. 경사하강법 (Gradient Descent)
- 실제값 & 예측값의 잔차가 최소값이 될 수 있을 때까지 순차적으로 값을 낮춰가는 수학적 연산 기법 | 알고리즘

# 텐서 = Tensor

- scalar : 0차원
- vector : 1차원 (행) -> index 순서
- matrix : 2차원 (행.열) -> 
- N-tensor : 3차원 ~ N차원

- 텐서는 축(axis)의 갯수(rank) : 1차원 텐서 = 1개의 축, 2차원 텐서 = 2개의 축
- 그렇다면, 현실세계의 데이터를 D/L의 모델에 입력하려면, 해당 데이터가 텐서의 형태로 변환!!
- How to make the data transform Tensor?

Keras, TensorFlow, PyTorch -> 3개의 라이브러리 활용해서 텐서로 데이터 변환

Keras :
- 딥러닝 구현을 상대적으로 쉽게 할 수 있도록 인터페이스 및 메뉴얼 제공 라이브러리
- 고차원의 딥러닝 모델을 구현, x (해당 라이브러리에 탑재된 기능의 제약, 한계)

TensorFlow :
- 구글에서 개발한 라이브러리
- 장점 : 구글 > 현재까지 개발된 딥러닝 라이브러리 가운데 가장 어려움
- 러닝커브 상당히 심함
- 오랜기간 딥러닝 학습 => 최고!!

PyTorch :
- 페이스북 AI 연구팀
- Keras, 기초모델 => 직관적인 형태의 코드
- 동적으로 딥러닝 모델 실행
- 비교적 나중에 딥러닝 학습, 연구 => 최고!!

# Numpy
- C언어로 만들어진 라이브러리, 고성능 수치연산계산을 위한 기능 제공
- 행렬 기반 계산에 유용한 라이브러리
- PyTorch의 문법이 Numpy와 굉장히 유사
- Data 기반에 분석가, 사이언티스트, 엔지니어 -> Numpy, PyTorch

- 파이썬, 행렬기반 데이터 생성, 계산 => pandas => 고차원 연산 x
- 파이썬 리스트를 활용한 데이터 프레임으로는 고차원 연산 x
- 넘파이 > 파이썬 내부 리스트 연산 2~3배 속도 빠르다 평가

In [1]:
!conda install pytorch torchvision torchaudio -c pytorch

zsh:1: command not found: conda


In [2]:
pip install torch torchvision torchaudio

INFO: pip is looking at multiple versions of torchaudio to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 809.1/809.1 kB 1.0 MB/s eta 0:00:00? eta -:--:--
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch

print(torch.__version__)

2.9.0


In [4]:
import torch

x = torch.rand(5, 3)
print(x)

tensor([[0.4822, 0.4751, 0.9597],
        [0.1051, 0.6457, 0.0150],
        [0.1825, 0.7296, 0.1393],
        [0.6495, 0.0883, 0.1365],
        [0.0050, 0.2064, 0.6583]])


In [6]:
# 0차원 텐서 (scala)

import numpy as np

data1 = np.array(10)
print(data1, data1.ndim, data1.shape)

# ndim : axis 축
# shape : 행렬의 정보

10 0 ()


In [8]:
# 1차원 텐서 (vector)

import torch

data1 = torch.FloatTensor([1, 2]) # 1, 2의 아이템(원소)를 가진 1차원(D) 텐서 선언
print(data1, data1.dim(), data1.shape)

data2 = torch.FloatTensor(3) # 임의의 원소를 3개 가진 1차원 텐서 선언
print(data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([0., 0., 0.]) 1 torch.Size([3])


In [11]:
# 2차원 텐서 (matrix)

import torch

data3 = torch.FloatTensor(3, 2) # 3 by 2
print(data3, data3.dim(), data3.shape)

data4 = torch.FloatTensor([[1, 2], [3, 4], [5, 6]])
print(data4, data4.dim(), data4.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [13]:
# 3차원 텐서 (N-tensor)

import torch

data5 = torch.FloatTensor(3, 2, 1)
print(data5, data5.dim(), data5.shape)

data6 = torch.FloatTensor([[[1], [2]], [[3], [4]], [[5], [6]]])
print(data6, data6.dim(), data6.shape)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]) 3 torch.Size([3, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


dtype = torch.float | torch.float32 => 32bit floating point
dtype = torch.double | torch.float64 => 64bit floating point
dtype = torch.half | torch.float16 => 16bit floating point

dtype = torch.uint8 => 8bit integer (unsigned)
dtype = torch.int8 => 8bit integer (signed)
dtype = torch.short | torch.int16 => 16bit integer (signed)
dtype = torch.int | torch.int32 => 32bit integer (signed)
dtype = torch.long | torch.int64 => 64bit integer (signed)

dtype = torch.bool => Boolean

In [18]:
import torch

data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2, 2, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)
data4 = torch.randn(2, 2, 3, dtype=torch.float)
data5 = torch.full((2, 4), 10)

In [16]:
print(data1.shape, data2.shape, data3.shape, data4.shape, data5.shape)

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3]) torch.Size([2, 4])


torch.zeros(x, y, z) : 0의 값으로 shape 모양의 텐서 생성
torch.ones(x, y, z) : 1의 값으로 shape 모양의 텐서 생성
torch.rand(x, y, z) : 0부터 1사이에 균일한 확률 분포로 랜덤값을 가진 (x, y, z) shape 모양의 텐서 생성
torch.randn(x, y, z) : 평균 0, 표준편차가 1이면서, 균일한 확률 분포로 랜덤값을 가진 (x, y, z) shape 모양의 텐서 생성
torch.full((x, y, z), a) : a값으로, shape 모양의 텐서 생성

torch.zeros_like(tensor) : 인자값으로 들어온 tensor 객체와 동일한 shape를 가지되, 각 원소값은 0으로 이루어진 텐서 생성
torch.ones_like(tensor) : 인자값으로 들어온 tensor 객체와 동일한 shape를 가지되, 각 원소값은 1로 이루어진 텐서 생성
torch.rand_like(tensor) : 인자값으로 들어온 tensor 객체와 동일한 shape를 가지되, 0부터 1사이에 균일한 확률 분포로 랜덤값을 가진 텐서 생성
torch.randn_like(tensor) : 인자값으로 들어온 tensor 객체와 동일한 shape를 가지되, 표준편차가 1이면서, 균일한 확률 분포로 랜덤값을 가진 텐서 생성
torch.full_like(tensor) : 인자값으로 들어온 tensor 객체와 동일한 shape를 가지되, 각 원소값이 a값으로 텐서 생성

torch.empty(x, y, z) : 초기화 되지 않은 값을 가진 (x, y) shape의 행렬를 생성

In [19]:
print(data1.ndim, data2.ndim, data3.ndim, data4.ndim, data5.ndim)

1 2 3 3 2


In [20]:
print(data1.dtype, data2.dtype, data3.dtype, data4.dtype, data5.dtype)

torch.float32 torch.float64 torch.float16 torch.float32 torch.int64


In [5]:
# 텐서의 배열 구조 변경 - 1

In [4]:
import torch

data1 = torch.DoubleTensor([[1, 2, 3], [4, 5, 6]])
print(data1)

data1 = data1.reshape(3, 2)
print(data1)

data1 = data1.reshape(2, -1) # -1은 열을 앞에서 정의한 행의 갯수에 맞춰서 자동으로 계산
print(data1)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [6]:
# 텐서의 배열 구조 변경 - 2

In [8]:
import torch

data1 = torch.DoubleTensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(data1.shape, "높이(k):", data1.size(0), "너비(n):", data1.size(1), "깊이(m):", data1.size(2))

torch.Size([2, 2, 3]) 높이(k): 2 너비(n): 2 깊이(m): 3


In [9]:
data1 = data1.view(2, -1) # -1은 2행은 지시한대로 진행, 열을 자동으로 계산
print(data1, data1.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64) torch.Size([2, 6])


In [10]:
data1 = data1.view(-1, 3)
print(data1, data1.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64) torch.Size([4, 3])


In [11]:
data1 = data1.view(3, 2, -1)
print(data1, data1.shape)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64) torch.Size([3, 2, 2])


In [ ]:
# 텐서 차원 압축 : 차원이 1인 경우, 해당 차원을 제거

In [14]:
import torch

data1 = torch.FloatTensor([[1], [2], [3]])
print(data1, data1.dim(), data1.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])


In [15]:
data2 = data1.squeeze()
print(data2, data2.dim(), data2.shape)

tensor([1., 2., 3.]) 1 torch.Size([3])


In [17]:
data3 = torch.randn(2, 1, 3, 4)
data3

tensor([[[[-1.0274, -1.3287,  3.4366,  1.2560],
          [-0.7534,  0.5711,  0.5921, -1.0415],
          [ 3.2018,  0.3100,  0.6563, -0.9397]]],


        [[[-0.4557,  0.5278,  0.7417, -1.2133],
          [-0.2387, -0.7471,  2.1777, -1.6720],
          [-0.5456,  0.7780,  0.1694, -0.7530]]]])

In [18]:
data4 = data3.squeeze()
print(data4, data4.shape)

tensor([[[-1.0274, -1.3287,  3.4366,  1.2560],
         [-0.7534,  0.5711,  0.5921, -1.0415],
         [ 3.2018,  0.3100,  0.6563, -0.9397]],

        [[-0.4557,  0.5278,  0.7417, -1.2133],
         [-0.2387, -0.7471,  2.1777, -1.6720],
         [-0.5456,  0.7780,  0.1694, -0.7530]]]) torch.Size([2, 3, 4])


In [19]:
# 텐서 차원 증가 : unsqueeze() : 특정 위치에 1인 차원을 추가

In [20]:
import torch

data1 = torch.FloatTensor([1, 2, 3])
print(data1, data1.dim(), data1.shape)

tensor([1., 2., 3.]) 1 torch.Size([3])


In [21]:
data2 = data1.unsqueeze(0)
print(data2, data2.dim(), data2.shape)

tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])


In [22]:
data3 = data1.unsqueeze(1)
print(data3, data3.dim(), data3.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])


In [23]:
# 텐서 타입 변환

In [28]:
import torch

data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2, 4, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)

print(data1.dtype, data2.dtype, data3.dtype)

data1 = data1.type(torch.float32)
data2 = data2.type(torch.int)
data3 = data3.type(torch.double)

print(data1.dtype, data2.dtype, data3.dtype)

torch.float32 torch.float64 torch.float16
torch.float32 torch.int32 torch.float64


In [29]:
data2

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [ ]:
# 전치 행렬 (Transpose)

In [30]:
data2 = data2.T
print(data2)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)


In [ ]:
# numpy & pytorch
# PyTorch는 numpy의 ndarray라는 데이터 타입을 GPU에서 실행할 수 있도록 개발된 라이브러리

In [33]:
import numpy as np
import torch

data1 = np.array([[1, 2], [3, 4]])
print(data1, type(data1))

data2 = torch.from_numpy(data1)
print(data2, type(data2))

data3 = data2.numpy()
print(data3, type(data3))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [34]:
# 텐서를 생성하는 기타 방법들

In [35]:
# 1차원 텐서를 생성하는 방법
# torch.arange(start, stop, step)

import torch

torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [36]:
torch.arange(1, 5)

tensor([1, 2, 3, 4])

In [37]:
torch.arange(1, 5, 2)

tensor([1, 3])

In [39]:
# linspace() : 1차원 텐서 = 행이라는 축을 가지고 텐서 데이터를 균등 생성
# torch.linspace(start, stop, count)

In [38]:
import torch

torch.linspace(1, 5, 4)

tensor([1.0000, 2.3333, 3.6667, 5.0000])

In [40]:
# 텐서 연산

In [44]:
import torch

data1 = torch.full((3, 3), 2)
data2 = torch.full((3, 3), 1)

print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [ ]:
# 만약, 2개의 텐서가 똑같은 행.렬을 가지고 있지 않은경우에는 연산이 불가능? x
# 조건에 따라서 가능하기도하다!!
# 앞 행렬의 열의 갯수와 뒷 행렬의 행의 갯수가 같으면 연산처리(곱셉) 가능!
# 3 x 2 | 2 x 3

In [45]:
import torch

data1 = torch.full((3, 2), 2)
data2 = torch.full((2, 3), 1)

torch.matmul(data1, data2)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [46]:
print(data1 * data2)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [48]:
# 텐서 연산 (브로드캐스팅)
# Java, C, TS : 업캐스팅, 다운캐스팅
# 상대적으로 큰 값을 처리할 수 있는 변수 > 작은 값을 처리할 수 있는 변수 할당
# 브로드 (Broad) : Broaden 동사의 파생명사
# 3 x 1 : 3행 1렬
# 1 x 3 : 1행 3렬
# 3 x 3 : 브로드캐스팅
# 서로 다른 원소의 개수를 가지고 있는 두개의 텐서가 존재하는데, 이 중 특정 차원의 원소 수가 1이거나, 존재하지 않는 경우에는 브로드캐스팅이 발생되었을 때, 차원이 확대가 될 수 있다

In [53]:
import torch

data1 = torch.FloatTensor([[1], [2], [3]])
data2 = torch.FloatTensor([1, 1, 1])
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)
print(data3)

torch.Size([3, 1]) torch.Size([3]) torch.Size([3, 3])
tensor([[2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])


In [54]:
import torch

data1 = torch.FloatTensor(10, 20, 4)
data2 = torch.FloatTensor(20, 4)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 20, 4]) torch.Size([20, 4]) torch.Size([10, 20, 4])


In [55]:
import torch

data1 = torch.FloatTensor(10, 1, 5)
data2 = torch.FloatTensor(10, 2, 1)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 1, 5]) torch.Size([10, 2, 1]) torch.Size([10, 2, 5])


In [56]:
data3

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [57]:
# 텐서
# 텐서 전치, 타입, 브로드캐스팅
# 텐서 연산처리
# 넘파이 & 텐서
# 연산완료 전제 -> 결과값을 찾아와야함!
# 텐서 -> 리스트 및 배열 -> 인덱스

In [59]:
# 텐서의 원소 접근 방법 (인덱싱)
# 텐서 데이터안에 있는 특정 원소(아이템)를 찾아오는 방법 및 기능을 indexing

In [66]:
import torch

data3 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(data3)
print(data3[1, 1])
print(data3[:, 1]) # : => 전체
print(data3[:, :])
print(data3[:1, :2])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([2., 5.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.]])
